node: database
http_proxy: 10.10.10.104:3128
databases: test1,test2,test3,drupal1,wpdb,redmine,jforum,jforum2
database_test1_user: test1
database_test1_password: test1
database_test2_user: test2
database_test2_password: test2
database_test3_user: test3
database_test3_password: test3
database_drupal1_user: drupal1
database_drupal1_password: droopal
database_drupal1_dump: drupal1
database_wpdb_user: wordpress
database_wpdb_password: secret
database_redmine_user: redmine
database_redmine_password: secret
database_jforum_user: jforum
database_jforum_password: tester123
database_jforum2_user: jforum2
database_jforum2_password: tester123
